name: Deploy to AWS Elastic Beanstalk

on:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      - run: npm install
      - run: npm run lint
      - run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::545009837640:role/GitHubActionsDeployRole
          aws-region: eu-north-1
      
      - name: Create deployment package
        run: |
          npm install --only=production
          zip -r deploy.zip . -x "*.git*" "node_modules/.cache/*" "tests/*" "*.test.js"
      
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v22
        with:
          aws_access_key: ${{ env.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ env.AWS_SECRET_ACCESS_KEY }}
          aws_session_token: ${{ env.AWS_SESSION_TOKEN }}
          application_name: express-aws-ci-cd-demo
          environment_name: demo-env
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
          wait_for_deployment: true
      
      - name: Health Check
        run: |
          sleep 30
          response=$(curl -s -o /dev/null -w "%{http_code}" http://demo-env.eba-7smfn5dj.eu-north-1.elasticbeanstalk.com/health)
          if [ $response -ne 200 ]; then
            echo "Health check failed with status $response"
            exit 1
          fi
          echo "Health check passed"